##########################################################
# Publish on npm.js
#
# @version 5.0.0
#
###########################################################

name: Publish
run-name: Publish package version ${{ github.ref_name }} on NPM.

on:
  push:
    tags:
      - "*"
      - "!*beta*"

jobs:
  publish:
    name: Publish on npm.js
    uses: lipemat/public-actions/.github/workflows/publish-package.yml@version/2
    with:
      beta: false
      nodeVersion: '20.11.0'
      withInstall: true
